# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleMarks',
            new_name='Marks',
        ),
    ]
